### ISSUE TITLE
TypeError: Cannot read property 'payload' of undefined

### ISSUE THREAD

**Issue by tkirchm** [coolchip/node-red-contrib-luxtronik2#8] opened 2022-01-02 10:30 UTC
Hello,

I get this error nearly every night and sometimes even up to five times.

> 2 Jan 02:00:23 - [red] Uncaught Exception:
2 Jan 02:00:23 - TypeError: Cannot read property 'payload' of undefined
at Luxtronik._processData (/home/pi/.node-red/node_modules/luxtronik2/luxtronik.js:332:74)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
nodered.service: Main process exited, code=exited, status=1/FAILURE
pam_unix(sudo:session): session closed for user root
nodered.service: Failed with result 'exit-code'.

NodeRed v2.0.6
node -v v14.18.1
node-red-contrib-luxtronik2 v0.5.1

**Comment by coolchip** [comment] 2022-01-04 10:21
Should be fixed with https://github.com/coolchip/luxtronik2/issues/28.
Try new version. v0.5.2

**Comment by tkirchm** [comment] 2022-01-05 09:42
Thank a lot. 
I just updated and will test it.

**Comment by tkirchm** [comment] 2022-01-06 20:54
Sorry for bothering you again but the error just changed.

6 Jan 03:50:30 - [red] Uncaught Exception:
6 Jan 03:50:30 - [error] TypeError: Cannot convert undefined or null to object
at hasOwnProperty ()
at Luxtronik._processData (/home/pi/.node-red/node_modules/luxtronik2/luxtronik.js:333:42)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
nodered.service: Main process exited, code=exited, status=1/FAILURE

**Comment by coolchip** [comment] 2022-02-13 10:28
Oh... you're right. I've done it the wrong way.
Try node-red-contrib-luxtronik2 v0.5.3

But keep in mind: The problem is not the node. Your luxtronik stops sending requested data back to node-red. Perhaps there is something with your network or your electricity provider shuts down your heatpump. 
With my bugfix now you should get an Error output from your node instead of an uncaught exception.

**Comment by tkirchm** [comment] 2022-02-15 14:43
Thank's. I'll test it next few day's.

It's strange I also used an ping node and only ask the heat pump when it is available and still I got uncaught exceptions. My electricity provider has no connection to my heat pump.

**Closed as completed** 2022-08-24 19:42 UTC
